# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: False
  config:
    entity: lewm
    project: lewm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: False

tensorboard:
  enabled: False
  config:
    save_dir: ${oc.env:SPT_CACHE_DIR,/home/hall/code/.stable-pretraining}/tensorboard
    name: ${output_model_name}
    version: ${subdir}
